/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n8.1.2-53-g1005b294ff-20260915"
#endif /* AVUTIL_FFVERSION_H */
